/**
 * Network helpers.
 *
 * Used only by `--bootstrap-config` and by the network-gated test. Nothing in
 * the hook path ever touches this module — a git hook that makes HTTP requests
 * is a git hook that hangs on a plane.
 */

import { humanize } from './markdown.mjs';
import { absoluteUrl } from './markdown.mjs';

const UA = 'llms-kit/1.0 (+https://github.com/base)';

/** Fetch with a timeout, returning null rather than throwing. */
export async function fetchText(url, { timeoutMs = 10000, method = 'GET' } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      method,
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'user-agent': UA },
    });
    if (!res.ok) return { ok: false, status: res.status, text: null };
    return { ok: true, status: res.status, text: method === 'HEAD' ? '' : await res.text() };
  } catch (err) {
    return { ok: false, status: 0, text: null, error: err.message };
  } finally {
    clearTimeout(timer);
  }
}

/** Run tasks with a bounded number in flight. */
export async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const i = cursor;
      cursor += 1;
      results[i] = await fn(items[i], i);
    }
  });
  await Promise.all(workers);
  return results;
}

function decodeEntities(text) {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&#x27;/gi, "'")
    .replace(/&nbsp;/g, ' ');
}

/** Pull <title> and <meta name="description"> out of rendered HTML. */
export function scrapeMeta(html) {
  const title = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1];
  const description =
    /<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i.exec(html)?.[1] ??
    /<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i.exec(html)?.[1];
  return {
    title: title ? decodeEntities(title).replace(/\s+/g, ' ').trim() : null,
    description: description ? decodeEntities(description).replace(/\s+/g, ' ').trim() : null,
  };
}

function quote(str) {
  return `'${String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Scrape every discovered route from the live origin and print an
 * llms.config.mjs skeleton.
 *
 * This is the escape hatch for a repo whose pages use `generateMetadata` (which
 * text analysis cannot read) or are `'use client'` with no layout metadata. It
 * turns "the extractor found nothing" from a blocker into a one-time five-minute
 * edit. It prints to stdout and never writes — the engineer reviews the
 * descriptions before committing them.
 */
export async function bootstrapConfig(ctx) {
  const { config, pages } = ctx;

  const scraped = await mapLimit(pages, 4, async (page) => {
    const url = absoluteUrl(config.origin, page.urlPath);
    const res = await fetchText(url);
    if (!res.ok) return { page, error: `HTTP ${res.status}${res.error ? ` (${res.error})` : ''}` };
    const meta = scrapeMeta(res.text);
    return { page, meta };
  });

  const lines = [
    '// Generated by: node scripts/llms.mjs --bootstrap-config',
    '//',
    '// Titles and descriptions were scraped from the live site. Review them —',
    '// a page title is often written for a browser tab, not for an agent.',
    '// Delete any entry whose page already exports usable `metadata`.',
    '',
    'export default {',
    `  origin: ${quote(config.origin)},`,
    '',
    '  routes: {',
  ];

  for (const { page, meta, error } of scraped) {
    if (error) {
      lines.push(`    // ${page.urlPath}: could not fetch (${error})`);
      continue;
    }
    const title = meta.title || humanize(page.segments[page.segments.length - 1]) || config.site.title;
    lines.push(`    ${quote(page.urlPath)}: {`);
    lines.push(`      title: ${quote(title)},`);
    if (meta.description) lines.push(`      description: ${quote(meta.description)},`);
    else lines.push('      // description: TODO — no meta description on the live page');
    lines.push('    },');
  }

  lines.push('  },', '};', '');
  return lines.join('\n');
}
