#!/usr/bin/env node
/**
 * Generate public/AGENTS.md — the PUBLIC agent routing document, served at
 * <origin>/AGENTS.md and modeled on https://www.base.org/AGENTS.md
 *
 * This is NOT the repo-root AGENTS.md. That file follows the agents.md spec
 * (setup commands, code style, PR conventions), is written by hand, and is
 * never touched by this script. See githooks/README.md for why both exist.
 *
 *   node scripts/agents.mjs            write the file
 *   node scripts/agents.mjs --check    write nothing, exit 1 if stale
 *   node scripts/agents.mjs --status   write nothing, always exit 0
 */

import path from 'node:path';
import {
  findRepoRoot, parseArgs, buildContext, writeIfChanged, wouldChange,
  reportCheck, reportStatus,
} from './lib/build.mjs';
import { absoluteUrl, collapseWhitespace, formatBytes, normalizeOutput } from './lib/markdown.mjs';
import { validateAgentsMd } from './lib/validate.mjs';

/** Section order, asserted by the tests so a reorder is a deliberate act. */
export const REQUIRED_SECTIONS = [
  'Agent routing rules',
  'Freshness and volatility',
  'Machine-readable endpoints',
  'Network reference',
  'Canonical documentation indexes',
  'Website routes',
  'Generation',
];

const BANNER = [
  '<!-- This file is generated by scripts/agents.mjs. Do not edit by hand. -->',
  '<!-- Hand-written repo conventions live in /AGENTS.md at the repo root. -->',
].join('\n');

/**
 * The routing rules are the point of this whole file. Everything else is
 * reference data an agent could theoretically find elsewhere; these rules are
 * the thing it cannot infer, and the thing that stops it inventing a chain ID.
 */
function renderRoutingRules(config) {
  const { title } = config.site;
  const ephemeral = (config.networks ?? []).filter((n) => n.ephemeral);

  const rules = [
    `Use ${config.originHost} for live network state: upgrade activation status, protocol changelog, snapshot availability, and developer network status.`,
    'Use docs.base.org for implementation detail: SDKs, contract addresses, RPC method semantics, and deployment guides.',
    'Use base.org for product, ecosystem, and use-case context.',
    'Never infer Base chain IDs or RPC URLs from third-party chain lists or from model memory. Use the network reference below.',
    'Prefer the JSON endpoints below over parsing rendered HTML. They are stable, typed, and cheaper to read.',
  ];

  for (const net of ephemeral) {
    rules.push(
      `${net.name.replace(/\s*\(.*\)$/, '')} is ephemeral. Never persist a chain ID, address, balance, or block height from it across sessions.`,
    );
  }

  rules.push(
    `If a ${config.originHost} page and a docs.base.org page disagree on schedule or status, ${config.originHost} is authoritative. On code and API shape, docs.base.org is authoritative. Flag the mismatch rather than silently picking one.`,
  );

  return ['## Agent routing rules', '', ...rules.map((r) => `- ${r}`)].join('\n');
}

/**
 * A table rather than prose, because the question an agent asks here is
 * lookup-shaped: "can I reuse what I fetched five minutes ago?"
 */
function renderFreshness(config, pages) {
  const rows = [];
  const seen = new Set();

  for (const [route, cadence] of Object.entries(config.freshness ?? {})) {
    rows.push({ path: route, cadence, guidance: guidanceFor(cadence) });
    seen.add(route);
  }
  for (const endpoint of config.endpoints ?? []) {
    const mirrors = Object.entries(config.freshness ?? {}).find(([r]) =>
      endpoint.url.includes(r.replace(/^\//, '')),
    );
    if (mirrors && !seen.has(endpoint.url)) {
      rows.push({ path: endpoint.url, cadence: mirrors[1], guidance: guidanceFor(mirrors[1]) });
      seen.add(endpoint.url);
    }
  }
  const rest = pages.map((p) => p.urlPath).filter((p) => !seen.has(p));
  if (rest.length > 0) {
    rows.push({ path: rest.join(', '), cadence: 'infrequent', guidance: 'stable within a session' });
  }

  return [
    '## Freshness and volatility',
    '',
    '| Path | Changes | Guidance |',
    '| --- | --- | --- |',
    ...rows.map((r) => `| ${r.path} | ${r.cadence} | ${r.guidance} |`),
  ].join('\n');
}

function guidanceFor(cadence) {
  if (cadence === 'daily') return 're-fetch every session; never cache across sessions';
  if (cadence === 'per release') return 're-fetch before stating an activation status';
  if (cadence === 'monthly') return 'stable within a session';
  return 'stable within a session';
}

function renderEndpoints(config) {
  if (!config.endpoints?.length) return null;
  const lines = config.endpoints.map((e) => {
    const url = absoluteUrl(config.origin, e.url);
    const shape = e.shape ? ` → \`${e.shape}\`` : '';
    return `- \`GET ${url}\`${shape}\n  ${collapseWhitespace(e.description)}`;
  });
  return ['## Machine-readable endpoints', '', ...lines].join('\n');
}

/**
 * One `### ` block per network. The validator checks that each block contains
 * both its own chain ID and its own RPC, which is what catches a transposed
 * 8453/84532 — the single most damaging error this file could ship.
 */
function renderNetworkReference(config) {
  const blocks = (config.networks ?? []).map((net) => {
    const lines = [`### ${net.name}`, ''];
    if (net.ephemeral) {
      lines.push('- Chain ID: not stable — read it from the site at request time');
      lines.push('- RPC: not stable — read it from the site at request time');
    } else {
      lines.push(`- Chain ID: \`${net.chainId}\``);
      lines.push(`- RPC: ${net.rpc}`);
    }
    if (net.explorer) lines.push(`- Explorer: ${net.explorer}`);
    if (net.faucet) lines.push(`- Faucet: ${net.faucet}`);
    if (net.guide) lines.push(`- Guide: ${net.guide}`);
    if (net.note) lines.push(`- Note: ${net.note}`);
    return lines.join('\n');
  });
  return `## Network reference\n\n${blocks.join('\n\n')}`;
}

function renderIndexes(config) {
  const r = config.related ?? {};
  const lines = [
    `- ${absoluteUrl(config.origin, '/llms.txt')} — this site's index`,
    `- ${absoluteUrl(config.origin, '/llms-full.txt')} — this site, full context`,
  ];
  if (r.docsLlms) lines.push(`- ${r.docsLlms} — Base documentation index`);
  if (r.docsLlmsFull) lines.push(`- ${r.docsLlmsFull} — Base documentation, full bundle`);
  if (r.docsAgents) lines.push(`- ${r.docsAgents} — Base documentation routing rules`);
  if (r.docsMcp) lines.push(`- ${r.docsMcp} — Base documentation MCP endpoint`);
  if (r.websiteAgents) lines.push(`- ${r.websiteAgents} — base.org product and ecosystem routing`);
  return ['## Canonical documentation indexes', '', ...lines].join('\n');
}

function renderRoutes(ctx) {
  const { config, groups } = ctx;
  const blocks = groups.map((group) => {
    const lines = group.routes.map((page) => {
      const url = absoluteUrl(config.origin, page.urlPath);
      const desc = page.description ? ` — ${page.description}` : '';
      return `- [${page.urlPath}](${url})${desc}`;
    });
    return [`**${group.title}**`, '', ...lines].join('\n');
  });
  return `## Website routes\n\nDiscovered from the Next.js app directory.\n\n${blocks.join('\n\n')}`;
}

function renderGeneration(config) {
  return [
    '## Generation',
    '',
    '- Script: `scripts/agents.mjs`',
    `- Output: \`${config.outputs.agents}\``,
    '- Run: `npm run agents` (or `pnpm agents` / `bun run agents`)',
    '- Trigger: include `agents.md` in a commit message; `githooks/post-commit` regenerates and commits.',
  ].join('\n');
}

export function renderAgentsMd(ctx) {
  const { config } = ctx;
  const summary = collapseWhitespace(config.site.agentsSummary ?? config.site.summary);

  // Ported from base/docs scripts/agents.js: a hard assertion, not a warning.
  // This string is the first thing an agent reads; if it has been edited into a
  // paragraph, that is a content bug worth failing the build over.
  if (summary.length > config.agentsDescriptionMaxChars) {
    throw new Error(
      `site.agentsSummary is ${summary.length} chars, max ${config.agentsDescriptionMaxChars}. ` +
        `Shorten it in llms.config.mjs.`,
    );
  }

  return [
    BANNER,
    '',
    `# ${config.site.title} AGENTS.md`,
    '',
    `> ${summary}`,
    '',
    `Machine-readable entry point for agents working with ${config.site.title} network state.`,
    '',
    renderRoutingRules(config),
    '',
    renderFreshness(config, ctx.pages),
    '',
    renderEndpoints(config),
    '',
    renderNetworkReference(config),
    '',
    renderIndexes(config),
    '',
    renderRoutes(ctx),
    '',
    renderGeneration(config),
    '',
  ]
    .filter((block) => block !== null)
    .join('\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = args.root ? path.resolve(args.root) : findRepoRoot(process.cwd());

  const ctx = await buildContext(repoRoot);
  const outPath = path.join(repoRoot, ctx.config.outputs.agents);
  const text = renderAgentsMd(ctx);

  const validation = validateAgentsMd(normalizeOutput(text), {
    requiredSections: REQUIRED_SECTIONS,
    networks: ctx.config.networks,
    descriptionMaxChars: ctx.config.agentsDescriptionMaxChars,
  });

  if (args.status) return reportStatus('agents', ctx, [ctx.config.outputs.agents]);
  if (args.check) {
    return reportCheck('agents', ctx, [
      { file: ctx.config.outputs.agents, check: wouldChange(outPath, text), validation },
    ]);
  }

  if (!validation.ok) {
    process.stderr.write('AGENTS.md failed validation, nothing written:\n');
    for (const err of validation.errors) process.stderr.write(`  ${err}\n`);
    return 1;
  }

  const result = writeIfChanged(outPath, text);
  const rel = path.relative(repoRoot, outPath);
  process.stdout.write(
    `${rel}  ${formatBytes(result.bytes).padStart(8)}  ${result.changed ? 'updated' : 'unchanged'}\n` +
    `${ctx.pages.length} routes, ${ctx.config.networks.length} networks\n`,
  );
  if (result.changed) process.stdout.write(`Review changes with: git diff ${rel}\n`);
  return 0;
}

const isMain = process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]));
if (isMain) {
  main()
    .then((code) => { process.exitCode = code; })
    .catch((err) => {
      process.stderr.write(`agents.mjs: ${err.message}\n`);
      process.exitCode = 1;
    });
}
